### ISSUE TITLE
No `contentLength` sent in POST method

### ISSUE THREAD

**Issue by tomaszpolanski** [brianegan/flutter_stetho#16]
When wrapping `HttpClientRequest` in `StethoHttpClientRequest` the `contentLength` is not correct as it is populated later on by the framework.
That results in not having proper content length sent to the backend and also not being displayed in DevTools.

**Comment by tonyraoul** [comment]
I had something similar today, not sure if it's related.

For some reason `contentLength` doesn't work as a header name and `content-length` works instead, If stetho is initialized.
However if it's not initialized `contentLength` is workink and `content-length` doesn't.

### Work around
use Dio library which is working in both cases like charm.

**Comment by brianegan** [comment]
Closing with the merge of the PR. Thanks again!
