### ISSUE TITLE
Error: 'StethoHttpClientResponse' can't implement both 'Stream<Uint8List>' and 'Stream<List<int>>'

### ISSUE THREAD

**Issue by Nobuo-N** [brianegan/flutter_stetho#30]
flutter_stetho 0.4.1 build error!!

Compiler message:
file:///Users/woodnyroom/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stetho-0.4.1/lib/src/http_client_response.dart:5:7: Error: 'StethoHttpClientResponse' can't implement both 'Stream<Uint8List>' and 'Stream<List<int>>'
 - 'Stream' is from 'dart:async'.
 - 'Uint8List' is from 'dart:typed_data'.
 - 'List' is from 'dart:core'.
class StethoHttpClientResponse extends StreamView<Uint8List>
      ^
file:///Users/woodnyroom/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_stetho-0.4.1/lib/src/http_client_request.dart:54:42: Error: The argument type 'HttpClientResponse' can't be assigned to the parameter type 'Stream<Uint8List>'.
 - 'HttpClientResponse' is from 'dart:_http'.
 - 'Stream' is from 'dart:async'.
 - 'Uint8List' is from 'dart:typed_data'.
Try changing the type of the parameter, or casting the argument to 'Stream<Uint8List>'.
      createResponseTransformer(id).bind(response),

**Comment by Nobuo-N** [comment]
flutter --version

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (5 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

**Comment by brianegan** [comment]
Please see the readme and use version 0.3.x
